apiVersion: apps/v1
kind: Deployment
metadata:
  name: triangle
spec:
  selector:
    matchLabels:
      app: triangle-backend
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: triangle-backend
        tier: backend
    spec:
      containers:
        - name: triangle-api
          image: "docker.io/phalligan/triangle-api:latest"
          ports:
            - name: http
              containerPort: 3002